/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.QiuzGame;

import javax.swing.JOptionPane;

/**
 *
 * @author HADEED
 */
public class Fram2 extends javax.swing.JFrame {

    /**
     * Creates new form Fram2
     */
    public Fram2() {
        initComponents();
    }
     public Fram2(String msg) {
        initComponents();
        showshere.setText(msg);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Qno1 = new javax.swing.ButtonGroup();
        Qno2 = new javax.swing.ButtonGroup();
        Qno3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        twohundredthree = new javax.swing.JRadioButton();
        twohundredsix = new javax.swing.JRadioButton();
        twohundredtwo = new javax.swing.JRadioButton();
        twohundredone = new javax.swing.JRadioButton();
        Questionno2 = new javax.swing.JLabel();
        kaharachi = new javax.swing.JRadioButton();
        kaharanchi = new javax.swing.JRadioButton();
        karachi = new javax.swing.JRadioButton();
        kolachi = new javax.swing.JRadioButton();
        Questionno1 = new javax.swing.JLabel();
        Questionno3 = new javax.swing.JLabel();
        Geofferychauser = new javax.swing.JRadioButton();
        Williamshakspear = new javax.swing.JRadioButton();
        Jhonmilton = new javax.swing.JRadioButton();
        Elizacook = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();
        showname = new javax.swing.JLabel();
        showshere = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("startingquiz");
        setBackground(new java.awt.Color(255, 102, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Qno2.add(twohundredthree);
        twohundredthree.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        twohundredthree.setText("203");
        twohundredthree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twohundredthreeActionPerformed(evt);
            }
        });

        Qno2.add(twohundredsix);
        twohundredsix.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        twohundredsix.setText("206");

        Qno2.add(twohundredtwo);
        twohundredtwo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        twohundredtwo.setText("202");

        Qno2.add(twohundredone);
        twohundredone.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        twohundredone.setText("201");
        twohundredone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twohundredoneActionPerformed(evt);
            }
        });

        Questionno2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Questionno2.setText("Q2: How many bones in the body ?");

        Qno1.add(kaharachi);
        kaharachi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kaharachi.setText("kaharachi");

        Qno1.add(kaharanchi);
        kaharanchi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kaharanchi.setText("kaharanchi");
        kaharanchi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaharanchiActionPerformed(evt);
            }
        });

        Qno1.add(karachi);
        karachi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        karachi.setText("Karachi");

        Qno1.add(kolachi);
        kolachi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kolachi.setText("Kolachi");
        kolachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolachiActionPerformed(evt);
            }
        });

        Questionno1.setBackground(new java.awt.Color(255, 102, 0));
        Questionno1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Questionno1.setText("Q1: What is the old name of karachi ?");

        Questionno3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Questionno3.setText("Q3: Who is known the father of English ?");

        Qno3.add(Geofferychauser);
        Geofferychauser.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Geofferychauser.setText("Geoffery Chaucr");
        Geofferychauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeofferychauserActionPerformed(evt);
            }
        });

        Qno3.add(Williamshakspear);
        Williamshakspear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Williamshakspear.setText("William Shakspear");
        Williamshakspear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WilliamshakspearActionPerformed(evt);
            }
        });

        Qno3.add(Jhonmilton);
        Jhonmilton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Jhonmilton.setText("John Milton");

        Qno3.add(Elizacook);
        Elizacook.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Elizacook.setText("Eliza Cook");

        next.setBackground(new java.awt.Color(0, 0, 0));
        next.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        next.setForeground(new java.awt.Color(204, 102, 0));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Questionno1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Questionno2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kolachi)
                                            .addComponent(kaharanchi))
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(karachi)
                                            .addComponent(kaharachi)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(twohundredone)
                                            .addComponent(twohundredthree))
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(twohundredsix)
                                            .addComponent(twohundredtwo))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Questionno3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jhonmilton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Geofferychauser, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Elizacook)
                            .addComponent(Williamshakspear))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Questionno1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(karachi)
                    .addComponent(kolachi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaharachi)
                    .addComponent(kaharanchi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Questionno2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(twohundredtwo)
                    .addComponent(twohundredone, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(twohundredthree)
                    .addComponent(twohundredsix))
                .addGap(12, 12, 12)
                .addComponent(Questionno3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Geofferychauser)
                    .addComponent(Williamshakspear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jhonmilton)
                    .addComponent(Elizacook))
                .addGap(32, 32, 32)
                .addComponent(next)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        showname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        showname.setForeground(new java.awt.Color(255, 102, 0));
        showname.setText("       NAME");
        showname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        showshere.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        showshere.setForeground(new java.awt.Color(255, 102, 0));
        showshere.setText("    ");
        showshere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(showname, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(showshere, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showshere, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 431));

        setSize(new java.awt.Dimension(553, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kaharanchiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaharanchiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kaharanchiActionPerformed

    private void kolachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolachiActionPerformed
        // TODO add your handling code here;
    }//GEN-LAST:event_kolachiActionPerformed

    private void twohundredthreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twohundredthreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twohundredthreeActionPerformed

    private void twohundredoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twohundredoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twohundredoneActionPerformed

    private void GeofferychauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeofferychauserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeofferychauserActionPerformed

    private void WilliamshakspearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WilliamshakspearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WilliamshakspearActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        Fram3 obj=new Fram3();
        if(!kolachi.isSelected()&&!kaharanchi.isSelected()&&!karachi.isSelected()&&!kaharachi.isSelected()
                ){
            JOptionPane.showMessageDialog(this, "Please select any one of them from Qno 1");
            obj.setVisible(false);
        }
        else if(!Elizacook.isSelected()
               && !Williamshakspear.isSelected()&&!Geofferychauser.isSelected()&& !Jhonmilton.isSelected()){
          JOptionPane.showMessageDialog(this, "Please select any one of them from Qno 2");
            obj.setVisible(false);
        }
        else if(!twohundredone.isSelected()&&!twohundredsix.isSelected()&&!twohundredthree.isSelected()&&!twohundredtwo.isSelected()){
            JOptionPane.showMessageDialog(this, "Please select any one of them from Qno 3");
            obj.setVisible(false);
        }
        else{
        obj.setVisible(true);
        }
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fram2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fram2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fram2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fram2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fram2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Elizacook;
    private javax.swing.JRadioButton Geofferychauser;
    private javax.swing.JRadioButton Jhonmilton;
    private javax.swing.ButtonGroup Qno1;
    private javax.swing.ButtonGroup Qno2;
    private javax.swing.ButtonGroup Qno3;
    private javax.swing.JLabel Questionno1;
    private javax.swing.JLabel Questionno2;
    private javax.swing.JLabel Questionno3;
    private javax.swing.JRadioButton Williamshakspear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton kaharachi;
    private javax.swing.JRadioButton kaharanchi;
    private javax.swing.JRadioButton karachi;
    private javax.swing.JRadioButton kolachi;
    private javax.swing.JButton next;
    private javax.swing.JLabel showname;
    private javax.swing.JLabel showshere;
    private javax.swing.JRadioButton twohundredone;
    private javax.swing.JRadioButton twohundredsix;
    private javax.swing.JRadioButton twohundredthree;
    private javax.swing.JRadioButton twohundredtwo;
    // End of variables declaration//GEN-END:variables
}
