/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.QiuzGame;

import javax.swing.JOptionPane;

/**
 *
 * @author HADEED
 */
public class Fram4 extends javax.swing.JFrame {

    /**
     * Creates new form Fram4
     */
    public Fram4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuestionNo8 = new javax.swing.ButtonGroup();
        QuestionNo9 = new javax.swing.ButtonGroup();
        QuestionNo10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Qno8 = new javax.swing.JLabel();
        One = new javax.swing.JRadioButton();
        Two = new javax.swing.JRadioButton();
        Three = new javax.swing.JRadioButton();
        Four = new javax.swing.JRadioButton();
        Qno9 = new javax.swing.JLabel();
        Button1 = new javax.swing.JRadioButton();
        Button2 = new javax.swing.JRadioButton();
        Button3 = new javax.swing.JRadioButton();
        Button4 = new javax.swing.JRadioButton();
        Qno10 = new javax.swing.JLabel();
        Yes = new javax.swing.JRadioButton();
        No = new javax.swing.JRadioButton();
        NoWay = new javax.swing.JRadioButton();
        Finish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0)));
        jPanel1.setForeground(new java.awt.Color(204, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Qno8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Qno8.setText("Q8 : How many eyes of Spider ?");

        QuestionNo8.add(One);
        One.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        One.setText("One");

        QuestionNo8.add(Two);
        Two.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Two.setText("Two");

        QuestionNo8.add(Three);
        Three.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Three.setText("Three");
        Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeActionPerformed(evt);
            }
        });

        QuestionNo8.add(Four);
        Four.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Four.setText("Four");

        Qno9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Qno9.setText("Q9 : How many Peter Parker in Spider man no way home ?");

        QuestionNo9.add(Button1);
        Button1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Button1.setText("1");

        QuestionNo9.add(Button2);
        Button2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Button2.setText("2");

        QuestionNo9.add(Button3);
        Button3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Button3.setText("3");

        QuestionNo9.add(Button4);
        Button4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Button4.setText("4");

        Qno10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Qno10.setText("Q10 : Is there a consept of Multiverse ?");

        QuestionNo10.add(Yes);
        Yes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Yes.setText("Yes");

        QuestionNo10.add(No);
        No.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        No.setText("No");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });

        QuestionNo10.add(NoWay);
        NoWay.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NoWay.setText("No Way");

        Finish.setBackground(new java.awt.Color(0, 0, 0));
        Finish.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        Finish.setForeground(new java.awt.Color(204, 102, 0));
        Finish.setText("Check Answer");
        Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Qno10, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Qno8, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(One)
                            .addComponent(Three))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Four)
                            .addComponent(Two)))
                    .addComponent(Qno9, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Button1)
                        .addGap(18, 18, 18)
                        .addComponent(Button2)
                        .addGap(18, 18, 18)
                        .addComponent(Button3)
                        .addGap(18, 18, 18)
                        .addComponent(Button4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Yes)
                        .addGap(18, 18, 18)
                        .addComponent(No)
                        .addGap(18, 18, 18)
                        .addComponent(NoWay)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Finish)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Qno8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(One)
                    .addComponent(Two))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Three)
                    .addComponent(Four))
                .addGap(18, 18, 18)
                .addComponent(Qno9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1)
                    .addComponent(Button2)
                    .addComponent(Button3)
                    .addComponent(Button4))
                .addGap(18, 18, 18)
                .addComponent(Qno10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Yes)
                    .addComponent(No)
                    .addComponent(NoWay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(Finish)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(553, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThreeActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoActionPerformed

    private void FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishActionPerformed
        // TODO add your handling code here:
          Fram5 obj = new Fram5();
          if(!One.isSelected()&&!Two.isSelected()&&!Three.isSelected()&&!Four.isSelected()){
               JOptionPane.showMessageDialog(this, "Please select any one of them from Qno 8");
              obj.setVisible(false);
          }
          else if(!Button1.isSelected()&&!Button2.isSelected()&&!Button3.isSelected()&&!Button4.isSelected()){
          JOptionPane.showMessageDialog(this, "Please select any one of them from Qno 9");
              obj.setVisible(false);
          }
          else if(!Yes.isSelected()&&!No.isSelected()&&!NoWay.isSelected()){
          JOptionPane.showMessageDialog(this, "Please select any one of them from Qno 10");
              obj.setVisible(false);
          }
          else{
          obj.setVisible(true);
          }
          
    }//GEN-LAST:event_FinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fram4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fram4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fram4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fram4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fram4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Button1;
    private javax.swing.JRadioButton Button2;
    private javax.swing.JRadioButton Button3;
    private javax.swing.JRadioButton Button4;
    private javax.swing.JButton Finish;
    private javax.swing.JRadioButton Four;
    private javax.swing.JRadioButton No;
    private javax.swing.JRadioButton NoWay;
    private javax.swing.JRadioButton One;
    private javax.swing.JLabel Qno10;
    private javax.swing.JLabel Qno8;
    private javax.swing.JLabel Qno9;
    private javax.swing.ButtonGroup QuestionNo10;
    private javax.swing.ButtonGroup QuestionNo8;
    private javax.swing.ButtonGroup QuestionNo9;
    private javax.swing.JRadioButton Three;
    private javax.swing.JRadioButton Two;
    private javax.swing.JRadioButton Yes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
