/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.QiuzGame;

import javax.swing.JOptionPane;

/**
 *
 * @author HADEED
 */
public class Fram3 extends javax.swing.JFrame {

    /**
     * Creates new form Fram3
     */
    public Fram3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuestionNo4 = new javax.swing.ButtonGroup();
        QuectionNo5 = new javax.swing.ButtonGroup();
        QuestionNo6 = new javax.swing.ButtonGroup();
        QuestionNo7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Qno4 = new javax.swing.JLabel();
        Elephant = new javax.swing.JRadioButton();
        loin = new javax.swing.JRadioButton();
        tiger = new javax.swing.JRadioButton();
        dolphin = new javax.swing.JRadioButton();
        Qno5 = new javax.swing.JLabel();
        corei3 = new javax.swing.JRadioButton();
        corei5 = new javax.swing.JRadioButton();
        corei7 = new javax.swing.JRadioButton();
        corei9 = new javax.swing.JRadioButton();
        Qno6 = new javax.swing.JLabel();
        Bugatti = new javax.swing.JRadioButton();
        Ferrari = new javax.swing.JRadioButton();
        HennessyvenomGT = new javax.swing.JRadioButton();
        Formulaone = new javax.swing.JRadioButton();
        Qno7 = new javax.swing.JLabel();
        one = new javax.swing.JRadioButton();
        two = new javax.swing.JRadioButton();
        three = new javax.swing.JRadioButton();
        four = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("            I hope that you are enjoying this Quiz");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Qno4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Qno4.setText("Q4: Which is the biggest animal ?");

        QuestionNo4.add(Elephant);
        Elephant.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Elephant.setText("Elephant");

        QuestionNo4.add(loin);
        loin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        loin.setText("Loin");
        loin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loinActionPerformed(evt);
            }
        });

        QuestionNo4.add(tiger);
        tiger.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tiger.setText("Tiger");

        QuestionNo4.add(dolphin);
        dolphin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dolphin.setText("Dolphin");

        Qno5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Qno5.setText("Q5: Which is the heaviest Core in it ?");

        QuectionNo5.add(corei3);
        corei3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        corei3.setText("Core i3");

        QuectionNo5.add(corei5);
        corei5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        corei5.setText("Core i5");

        QuectionNo5.add(corei7);
        corei7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        corei7.setText("Core i7");

        QuectionNo5.add(corei9);
        corei9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        corei9.setText("Core i9");

        Qno6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Qno6.setText("Q6: Which is the most fastest car in the world ?");

        QuestionNo6.add(Bugatti);
        Bugatti.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Bugatti.setText("Bugatti");
        Bugatti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BugattiActionPerformed(evt);
            }
        });

        QuestionNo6.add(Ferrari);
        Ferrari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ferrari.setText("Ferrari");
        Ferrari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FerrariActionPerformed(evt);
            }
        });

        QuestionNo6.add(HennessyvenomGT);
        HennessyvenomGT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        HennessyvenomGT.setText("Hennessey Venom GT");
        HennessyvenomGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HennessyvenomGTActionPerformed(evt);
            }
        });

        QuestionNo6.add(Formulaone);
        Formulaone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Formulaone.setText("Formula One");
        Formulaone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormulaoneActionPerformed(evt);
            }
        });

        Qno7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Qno7.setText("Q7: In how many parts is America divided ?");

        QuestionNo7.add(one);
        one.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        one.setText("One");

        QuestionNo7.add(two);
        two.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        two.setText("Two");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        QuestionNo7.add(three);
        three.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        three.setText("Three");

        QuestionNo7.add(four);
        four.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        four.setText("Four");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 102, 0));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Qno5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Qno4, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Elephant)
                                    .addComponent(tiger))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dolphin)
                                    .addComponent(loin)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(corei3)
                                    .addComponent(corei7))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(corei9)
                                    .addComponent(corei5)))
                            .addComponent(Qno6, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HennessyvenomGT)
                                    .addComponent(Bugatti, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Formulaone)
                                    .addComponent(Ferrari)))
                            .addComponent(Qno7, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(one)
                            .addComponent(three))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(four)
                            .addComponent(two))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Qno4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Elephant)
                    .addComponent(loin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiger)
                    .addComponent(dolphin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Qno5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corei3)
                    .addComponent(corei5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corei7)
                    .addComponent(corei9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Qno6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bugatti)
                    .addComponent(Ferrari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HennessyvenomGT)
                    .addComponent(Formulaone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Qno7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(one)
                            .addComponent(two))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(three)
                            .addComponent(four))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(24, 24, 24))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(553, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loinActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Fram4 obj=new Fram4();
        if(!Elephant.isSelected()&&!loin.isSelected()&&!dolphin.isSelected()&&!tiger.isSelected()){
             JOptionPane.showMessageDialog(this, "Please select any one of them from Qno 4");
            obj.setVisible(false);
        }
        else if(!corei3.isSelected()&&!corei5.isSelected()&&!corei7.isSelected()&&!corei9.isSelected()){
            JOptionPane.showMessageDialog(this, "Please select any one of them from Qno 5");
            obj.setVisible(false);
        }
        else if(!Bugatti.isSelected()&&!Ferrari.isSelected()&&!Formulaone.isSelected()&&!HennessyvenomGT.isSelected()){
          JOptionPane.showMessageDialog(this, "Please select any one of them from Qno 6");
            obj.setVisible(false);
        }
        else if(!one.isSelected()&&!two.isSelected()&&!three.isSelected()&&!four.isSelected()){
           JOptionPane.showMessageDialog(this, "Please select any one of them from Qno 7");
            obj.setVisible(false);
        }
        else{
        obj.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BugattiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BugattiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BugattiActionPerformed

    private void FerrariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FerrariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FerrariActionPerformed

    private void HennessyvenomGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HennessyvenomGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HennessyvenomGTActionPerformed

    private void FormulaoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormulaoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormulaoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fram3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fram3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fram3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fram3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fram3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bugatti;
    private javax.swing.JRadioButton Elephant;
    private javax.swing.JRadioButton Ferrari;
    private javax.swing.JRadioButton Formulaone;
    private javax.swing.JRadioButton HennessyvenomGT;
    private javax.swing.JLabel Qno4;
    private javax.swing.JLabel Qno5;
    private javax.swing.JLabel Qno6;
    private javax.swing.JLabel Qno7;
    private javax.swing.ButtonGroup QuectionNo5;
    private javax.swing.ButtonGroup QuestionNo4;
    private javax.swing.ButtonGroup QuestionNo6;
    private javax.swing.ButtonGroup QuestionNo7;
    private javax.swing.JRadioButton corei3;
    private javax.swing.JRadioButton corei5;
    private javax.swing.JRadioButton corei7;
    private javax.swing.JRadioButton corei9;
    private javax.swing.JRadioButton dolphin;
    private javax.swing.JRadioButton four;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton loin;
    private javax.swing.JRadioButton one;
    private javax.swing.JRadioButton three;
    private javax.swing.JRadioButton tiger;
    private javax.swing.JRadioButton two;
    // End of variables declaration//GEN-END:variables
}
