/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.QiuzGame;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HADEED
 */
public class TitlePage extends javax.swing.JFrame {

    /**
     * Creates new form TitlePage
     */
    public TitlePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javax.swing.JLabel();
        Pbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt.setFont(new java.awt.Font("Segoe Script", 2, 18)); // NOI18N
        txt.setForeground(new java.awt.Color(51, 153, 0));
        txt.setText("jLabel2");
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 260, 70, -1));

        Pbar.setForeground(new java.awt.Color(51, 153, 0));
        getContentPane().add(Pbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 204, 230, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HADEED\\Desktop\\HD-wallpaper-welcome-black-blue-information-live-loading-modern-pattern-tech-technology-themes-thumbnail.jpg")); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 490));

        setSize(new java.awt.Dimension(354, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        TitlePage T = new TitlePage();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                T.setVisible(true);
            }
        });
        FrontPage f = new FrontPage();
        
     try{      
           for(int i = 0; i<=100; i++)
            {
                Thread.sleep(100);
                 T.Pbar.setValue(i);
                 T.txt.setText(String.valueOf(i)+"%");
                 if(i==100)
                 {
                 T.setVisible(false);
                 T.dispose();
            }
            }
     }
            catch (InterruptedException ex) {
                Logger.getLogger(TitlePage.class.getName()).log(Level.SEVERE, null, ex);
            }
                  f.setVisible(true);
                  T.dispose();  
            }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Pbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txt;
    // End of variables declaration//GEN-END:variables
}
